### ISSUE TITLE
String literals inside of subshell expansions sometimes don't highlight correctly

### ISSUE THREAD

**Issue by stevekuznetsov** [jfcherng/Sublime-ShellScriptImproved#34] opened 2016-10-20 17:38 UTC
The function:

``` sh
function os::log::warn() {
    os::text::yellow "$( printf '[WARNING] %s\n' "$*" )" 1>&2
}
```

Highlights like this:
![printf](https://cloud.githubusercontent.com/assets/7328370/19571024/68c3196c-96ca-11e6-8b5f-692eacaeec59.png)

The literal text `'[WARNING] %s\n'` is incorrectly highlighted.

**Comment by jfcherng** [comment] 2016-10-20 18:54
![image](https://cloud.githubusercontent.com/assets/6594915/19573617/97f59d26-9739-11e6-8e60-f6cf578cbadf.png)

This is what I see with my color scheme, i.e., [the bundled dark one](https://github.com/jfcherng/Sublime-ShellScriptImproved/blob/master/color_schemes/dark.tmTheme).

I have checked scopes of your codes won't cause a parsing problem so I may consider there is nothing to be fixed in `ShellScriptImproved`. The problem you encountered could be your color scheme is lacking in some scopes. Most of problems are caused by [meta.reset.color](https://github.com/jfcherng/Sublime-ShellScriptImproved/blob/master/color_schemes/dark.tmTheme#L505-L515) and [string](https://github.com/jfcherng/Sublime-ShellScriptImproved/blob/master/color_schemes/dark.tmTheme#L57-L66). But `meta.reset.color` will never be perfect since it's just a workaround for complex and nested scopes.

**Comment by stevekuznetsov** [comment] 2016-10-20 20:37
Interesting. What specific scope is that string being labeled with? I will check to see how the color scheme handles it.

**Comment by jfcherng** [comment] 2016-10-21 07:59
![image](https://cloud.githubusercontent.com/assets/6594915/19590998/68ee23d6-97a7-11e6-895d-921408ece9de.png)

You could use [ScopeHunter](https://packagecontrol.io/packages/ScopeHunter) to check it. `ScopeHunter` provides everything you need about scopes. A helpful one is which scope is selected in your color scheme.

**Comment by jfcherng** [comment] 2017-04-07 18:18
Gonna close this due to inactiveness.

**Closed as completed by jfcherng** 2017-04-07 18:18 UTC
Labels: invalid
