### ISSUE TITLE
Colors in Array; true statement

### ISSUE THREAD

**Issue by SonGokussj4** [jfcherng/Sublime-ShellScriptImproved#7] opened 2016-04-13 09:06 UTC
Hello, would it be possible to improve arrays and True Statement?
It's done well in original _ShellScript (Bash)_
- [Syntax ShellScript (Bash)](http://imgur.com/a/RSOsf) (imgur link)

Yours is not highlighting the _true_ statement and for some reason it's highlighting every **1st letter next to -** on a new line in Array.
- [Syntax ShellScript Improved](http://imgur.com/a/KcHeH) (imgur link)

If it's an intention, then ok :-)
Still like your syntax more

**Comment by jfcherng** [comment] 2016-04-13 09:28
``` bash
var=true
#   ^^^^ this is plain text
```

I am not sure about that. That `true` is actually plain text and has no special meaning grammarically.

## 

The second one would be fixed in the next release.

## 

By the way, it would be better that you post your codes directly so people who want to help you don't have to type them manually. Sometimes, people do not help others because of laziness.

**Comment by SonGokussj4** [comment] 2016-04-13 10:15
You mean don't use _imgur_ to show you the code but to type it here instead?
I agree with this but I didn't find another way to **show** you the **colors** of those two diferences.

If I didn't understand your comment about "post your codes directly" correctly, I appologize.

P.S. Thanks for the second one !
About the first one: I see. I agree, it's just a text, it's not a boolean like in Python.
It was just a thought that it would be nice to "color it" because many people are using it as "like boolean".
But of course, if you color it to semething different then it's syntax-color error. So ok, forget it :-) You're right.

**Comment by jfcherng** [comment] 2016-04-13 10:34
> You mean don't use _imgur_ to show you the code but to type it here instead?

Yes, when people try to help you, they have to reproduce your "environment."
If you post the codes here, then it's a copy-and-paste thing which is easy.
Moreover, Github host images. You can just drag-and-drop or directly paste your images here.

> P.S. Thanks for the second one !

It's actually my stupid.

> About the first one: I see. I agree, it's just a text, it's not a boolean like in Python.
> It was just a thought that it would be nice to "color it" because many people are using it as "like boolean".

Maybe, I can add special scopes for them and leave users adding colors by themselves.

**Comment by jfcherng** [comment] 2016-04-13 12:35
![image](https://cloud.githubusercontent.com/assets/6594915/14493262/1fe1ccfa-01b7-11e6-9844-eb43c74b4b1e.png)

So I add special scopes for `true` and `false` just like `$` in Javascript.

**Comment by jfcherng** [comment] 2016-04-13 12:36
Above changes should be available in 1.1.0.

**Closed as completed by jfcherng** 2016-04-13 12:36 UTC
Labels: enhancement, highlighting, fixed
